### ISSUE TITLE
Misses nillable = true

### ISSUE THREAD

**Issue by jmattheis** [dmak/jaxb-xew-plugin#45]
You'r plugin misses the nillable = true on elements that get unwrapped
Could you have a look at it?
http://stackoverflow.com/a/34827748/4244993

**Comment by dmak** [comment]
Thanks, that is a valid point. Could you try [`jaxb-xew-plugin:1.6-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.6-SNAPSHOT/jaxb-xew-plugin-1.6-20160118.160123-1.jar)? The issue should be fixed there.

**Comment by jmattheis** [comment]
I used `mvn install:install-file` for getting the jar inside my local repository, but when i now run the code gen it's failing with:
```
[ERROR] Failed to execute goal org.apache.cxf:cxf-codegen-plugin:3.0.5:wsdl2java (generate-sources) on project fff-ws-client-cxf: org/apache/commons/lang3/reflect/FieldUtils: org.apache.commons.lang3.
reflect.FieldUtils -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.cxf:cxf-codegen-plugin:3.0.5:wsdl2java (generate-sources) on project fff-ws-client-cxf: org/apache/commons/lan
g3/reflect/FieldUtils
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org/apache/commons/lang3/reflect/FieldUtils
        at org.apache.cxf.maven_plugin.wsdl2java.WSDL2JavaMojo.generate(WSDL2JavaMojo.java:447)
        at org.apache.cxf.maven_plugin.AbstractCodegenMoho.execute(AbstractCodegenMoho.java:319)
        at org.apache.cxf.maven_plugin.wsdl2java.WSDL2JavaMojo.execute(WSDL2JavaMojo.java:524)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/reflect/FieldUtils
        at com.sun.tools.xjc.addon.xew.CommonUtils.getPrivateField(CommonUtils.java:196)
        at com.sun.tools.xjc.addon.xew.CommonUtils.getAnnotationMember(CommonUtils.java:78)
        at com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin.checkAnnotationReference(XmlElementWrapperPlugin.java:1183)
        at com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin.runInternal(XmlElementWrapperPlugin.java:459)
        at com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin.run(XmlElementWrapperPlugin.java:319)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:284)
        at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:95)
        at org.apache.cxf.tools.wsdlto.databinding.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:460)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.generateTypes(WSDLToJavaContainer.java:726)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.processWsdl(WSDLToJavaContainer.java:270)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:164)
        at org.apache.cxf.tools.wsdlto.WSDLToJavaContainer.execute(WSDLToJavaContainer.java:412)
        at org.apache.cxf.tools.common.toolspec.ToolRunner.runTool(ToolRunner.java:103)
        at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:113)
        at org.apache.cxf.tools.wsdlto.WSDLToJava.run(WSDLToJava.java:86)
        at org.apache.cxf.maven_plugin.wsdl2java.WSDL2JavaMojo.generate(WSDL2JavaMojo.java:427)
        ... 23 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.reflect.FieldUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 40 more
```
maybe I did something wrong?

**Comment by dmak** [comment]
You need to overwrite POM which was auto-generated by Maven, with [`jaxb-xew-plugin-1.7-xxx.pom`](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.7-SNAPSHOT/jaxb-xew-plugin-1.7-20160118.164504-1.pom). The version suffix `xxx` should match the version of JAR.

**Comment by jmattheis** [comment]
Ok, I tried it and all works well. Can be closed then.

**Comment by dmak** [comment]
The fix is in repo and will be a part of next release 1.7, which I plan to make in end of March beginning of April.
